name: Opam Continuous Integration

on:
  pull_request:
  push:
    branches: [main]

jobs:
 build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - ocaml-base-compiler.4.14.2
          - ocaml-base-compiler.5.4.0
    steps:
      - uses: actions/checkout@v5

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Restore opam cache
        id: opam-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.opam
            $GITHUB_WORKSPACE/_opam
          key: opam-${{ matrix.os }}-${{ matrix.ocaml-compiler }}-${{ hashFiles('*.opam') }}

      - name: Install opam dependencies (with tests if supported)
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            opam install --deps-only .
          else
            opam install --deps-only --with-test .
          fi

      - name: Build project
        run: opam exec -- dune build @install

      - name: Run tests
        if: runner.os != 'Windows'
        run: opam exec -- dune test

      - name: Save opam cache 
        uses: actions/cache/restore@v4
        with: 
          path: | 
            ~/.opam 
            $GITHUB_WORKSPACE/_opam 
          key: opam-${{ matrix.os }}-${{ matrix.ocaml-compiler }}-${{ hashFiles('*.opam') }}


